input:
  equipment: example/Equipment_c_порядковыми_номерами_Scada_действует_с_02_08_2023.xlsx
  setups: example/setups_{}.xlsx
  tasks: example/tasks_{}.xlsx

output:
  daily_tasks: example/result_{}.xlsx

rules:
  human_labor_limit: 12
  machine_labor_limit: 11
  days_number: 10
  dept_id: '1052'