input:
  equipment: example/equipment1052.xlsx
  setups: example/setups_{}.xlsx
  tasks: example/tasks_{}.xlsx
  phase: example/phase.csv
  cycle: example/cycles.csv

output:
  daily_tasks: example/result_{}.xlsx
  raport: example/raport.json

rules:
  human_labor_limit: 12
  machine_labor_limit: 11
  days_number: 1
  dept_id: '1052'
  step: 12