input:
  equipment: example/equipment1052.xlsx
  setups: example/setups_{}.xlsx
  tasks: example/tasks_{}.xlsx

output:
  daily_tasks: example/result_{}.xlsx

rules:
  human_labor_limit: 12
  machine_labor_limit: 11
  days_number: 10
  dept_id: '1052'